language: python
python:
   - "2.7"
   - "3.5"
   - "3.6"

branches:
   only:
    - master
    - devel

before_install:
    - pip install -U pip wheel

install:
    - pip install -U pytest
    - pip install .
    - ./travis_install.sh
    - pip install codecov
    - pip install pytest-cov

script: travis_wait 120 py.test --cov

after_success:
    - codecov
